version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: storj_nginx
    ports:
      - "28000:80"  # Changeable port mapping
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/var/www/html
    depends_on:
      - php
    restart: always

  php:
    build: ./php
    container_name: storj_php
    volumes:
      - ./www:/var/www/html
    environment:
      STORJ_DASHBOARD_IP_PORT: "${STORJ_DASHBOARD_IP_PORT}"
      AUTH_CODE: "${AUTH_CODE}"
    restart: always
    entrypoint: ["/bin/bash", "-c", "cron && php-fpm"]

volumes:
  www:
