version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: controlpanel_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/var/www/html
    depends_on:
      - php
    restart: always

  php:
    image: php:8.2-fpm
    container_name: controlpanel_php
    volumes:
      - ./www:/var/www/html
    restart: always
