version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: controlpanel_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../controlpanel_site:/var/www/html
      - ../../controlpanel_includes:/var/www/html/includes
      - ../servers/www:/var/www/html/servers
      - ../servers:/var/www/d-config
    depends_on:
      - php
    restart: always

  php:
    image: php:fpm
    container_name: controlpanel_php
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../controlpanel_site:/var/www/html
      - ../../controlpanel_includes:/var/www/html/includes
      - ../servers/www:/var/www/html/servers
      - ../servers:/var/www/d-config
    restart: always

    command: ["/bin/sh", "-c", "chmod -R 777 /var/www && chown -R www-data:www-data /var/www && php-fpm"]
