version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: controlpanel_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../controlpanel_site:/var/www/html
      - ../../controlpanel_includes:/var/www/html/includes
      - ../servers/www:/var/www/html/servers/
    depends_on:
      - php
    restart: always

  php:
    image: php:8.2-fpm
    container_name: controlpanel_php
    volumes:
      - ../../controlpanel_site:/var/www/html
      - ../../controlpanel_includes:/var/www/html/includes
      - ../servers/www:/var/www/html/servers/
    restart: always
    command: ["/bin/sh", "-c", "chmod -R 777 /var/www/html && chown -R www-data:www-data /var/www/html && php-fpm"]
